### ISSUE TITLE
> 我觉得还是敬告所有华人，尤其是各位学生，仔细考虑下什么是正确的事，而不是每天像机器一样接受管控下的媒体所产出的信息，然后用那被绑架了的道德观去谴责别人

### ISSUE THREAD

**Issue by 1084233320** [uvipen/ASCII-generator#65]
> 我觉得还是敬告所有华人，尤其是各位学生，仔细考虑下什么是正确的事，而不是每天像机器一样接受管控下的媒体所产出的信息，然后用那被绑架了的道德观去谴责别人

我觉得还是敬告所有海外华人（包括赛博出国），尤其是各位学生，仔细考虑下什么是正确的事，而不是每天像机器一样接受不受管控下的媒体所产出的信息，然后用那被绑架了的道德观去谴责别人

_Originally posted by @gfhdhytghd in https://github.com/vietnh1009/ASCII-generator/issues/25#issuecomment-2497909176_

You are also using your moral values to kidnap others, aren't you?

**Comment by ProgaStudio** [comment]
So?

**Comment by TTChenYou** [comment]
Your issue does not comply with the spirit of the GitHub Community Code of Conduct. Please close this issue.

**Comment by B19J78** [comment]
What issue

Elizabeth Johnson

**Comment by gfhdhytghd** [comment]
> ```
>           > 我觉得还是敬告所有华人，尤其是各位学生，仔细考虑下什么是正确的事，而不是每天像机器一样接受管控下的媒体所产出的信息，然后用那被绑架了的道德观去谴责别人
> ```
> 
> 我觉得还是敬告所有海外华人（包括赛博出国），尤其是各位学生，仔细考虑下什么是正确的事，而不是每天像机器一样接受不受管控下的媒体所产出的信息，然后用那被绑架了的道德观去谴责别人
> 
> _Originally posted by @gfhdhytghd in [#25 (comment)](https://github.com/vietnh1009/ASCII-generator/issues/25#issuecomment-2497909176)最初由 in [#25 (comment)](https://github.com/vietnh1009/ASCII-generator/issues/25#issuecomment-2497909176) 发布_
> 
> You are also using your moral values to kidnap others, aren't you?你也在利用你的道德价值观来绑架别人，不是吗？

Extremes cancel each other out to neutralize the environment

**Comment by jojojo-zzl** [comment]
赛博姜萍daisuki

**Comment by Lvshujun0918** [comment]
so you think you are right? for what? WHY YOU HAVE PERMISSION TO COMMAND US?
